services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust-webapp
    container_name: rust-webapp
    volumes:
      - ./api:/api
    working_dir: /api
    env_file:
      - .env
    tty: true
    ports:
      - 8080:8080
    command: /bin/bash -c "cargo run"
